version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=discourse
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=discourse
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:5.0.0
    # command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
